name: Update Apple Podcast Feed

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 🧠 Important fix for rebase & push

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install axios xml2js

      - name: Generate Updated feed.xml
        run: node generate-feed.js

      - name: Commit & Push feed.xml if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add feed.xml || true
          git diff --cached --quiet && echo "No changes" && exit 0
          git commit -m "🤖 Update feed.xml (auto)"
          git pull --rebase || true
          git push || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
